export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";

export const ALBUM_FETCH_DATA_SUCCESS = "ALBUM_FETCH_DATA_SUCCESS";
export const ALBUM_DETAILS_FETCH_DATA_SUCCESS =
  "ALBUM_DETAILS_FETCH_DATA_SUCCESS";
export const ALBUM_PHOTOS_FETCH_DATA_SUCCESS =
  "ALBUM_PHOTOS_FETCH_DATA_SUCCESS";

export const USER_FETCH_DATA_SUCCESS = "USER_FETCH_DATA_SUCCESS";
export const USER_DETAILS_FETCH_DATA_SUCCESS =
  "USER_DETAILS_FETCH_DATA_SUCCESSS";

export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCHING = "FETCHING";
export const ERROR = "ERROR";
